name: CI Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  android-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do c칩digo
        uses: actions/checkout@v3

      - name: Instalar JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache do Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Rodar testes unit치rios
        run: ./gradlew testDebugUnitTest

      - name: Executar lint est치tico
        run: ./gradlew lintDebug

  build-apk:
    needs: android-ci
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do c칩digo
        uses: actions/checkout@v3

      - name: Instalar JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache do Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Limpar build anterior
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Publicar APK como artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
